FROM node:12.16.2-stretch-slim as builder

RUN apt-get -y update && \
    apt-get -y install git python build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/man/?? /usr/share/man/??_*

WORKDIR /client

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

CMD ["npm", "start"]