version: "3.7"

services:
  server-migrations:
    build:
      context: "server"
    command: npm run migrate
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ipfs:ipfs@db/ipfs

  server-backend:
    build:
      context: "server"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ipfs:ipfs@db/ipfs
      - SERVER_PORT=4000
      - JWT_SECRET=SUPER_SECRET
      - REDIS_URL=http://redis
      - REDIS_PORT=6379
    ports:
      - "4000:4000"

  proxy-backend:
    build:
      context: "proxy-server"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ipfs:ipfs@db/ipfs
      - SERVER_PORT=5000
      - IPFS_URL=http://ipfs:5001
      - REDIS_URL=http://redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=ipfs
      - POSTGRES_PASSWORD=ipfs
      - POSTGRES_DB=ipfs
    volumes:
      - "db-postgresd:/var/lib/postgresql/data"

  ipfs:
    image: ipfs/go-ipfs
    environment:
      - IPFS_PROFILE=server

  redis:
    image: redis

volumes:
  db-postgresd:
